name: angleBrackets
owner: Stephen Hukish
position: Web Developer/Designer
email: stephen.hukish@gmail.com
github: github.com/dahukish
twitter: twitter.com/stephenhukish
linkedin: http://ca.linkedin.com/pub/stephen-hukish/1b/a03/33/
